version: "3.8"

services:
  backend:
    build: ./backend
    container_name: tuvi_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/gemini-profile-data:/app/gemini-profile-data
    restart: always

  frontend:
    build: ./frontend
    container_name: tuvi_frontend
    ports:
      - "5173:5173"
    restart: always